export const ClothesArr = [
  {
    id: 1,
    path: "../../public/clotheImg/arter.jpeg",
    alt: "arter",
    price: "500$",
    desc: "24k Lt Atom Hoodie",
    type: "Outerwear",
  },
  {
    id: 2,
    path: "../../public/clotheImg/alyx.webp",
    alt: "alyx",
    price: "300$",
    desc: "1017 ALYX 9SM Drawstring Hoodie",
    type: "Outerwear",
  },
  {
    id: 3,
    path: "../../public/clotheImg/fog.webp",
    alt: "fog",
    price: "200$",
    desc: "Fear Of God Cement Hoodie",
    type: "Outerwear",
  },
  {
    id: 4,
    path: "../../public/clotheImg/fog.webp",
    alt: "fog",
    price: "200$",
    desc: "Fear Of God Cement Hoodie",
    type: "Outerwear",
  },
  {
    id: 5,
    path: "../../public/clotheImg/bjork-tee.jpg",
    alt: "bjork",
    price: "250$",
    desc: "Bjork Tee",
    type: "Shirt",
  },
  {
    id: 6,
    path: "../../public/clotheImg/bsrr.jpeg",
    alt: "bstroy",
    price: "280$",
    desc: "Bstroy Tee",
    type: "Shirt",
  },
  {
    id: 7,
    path: "../../public/clotheImg/glam.webp",
    alt: "bstroy",
    price: "350$",
    desc: "Hyseterics Glamour Snake Denim",
    type: "Pants",
  },
  {
    id: 8,
    path: "../../public/clotheImg/glam2.webp",
    alt: "bstroy",
    price: "350$",
    desc: "Hyseterics Glamour Kinky Denim",
    type: "Pants",
  },
];
